version: "3.9"

services:
  flask-app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=/app/app.py
    volumes:
      - .:/app
    working_dir: /app
    command: python app.py
